### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by michelson** [chaskiq/chaskiq#1]
+ [x] handle channel connection disconnection properly
+ [x] handle channel id by convo properly 
- [x] refresh message settings when change tab

------

 - [x] display metrics
 - [x] fix dante tooltip
 - [x] adapt dante tooltip with bold , h3, h1 
 - [x] embeds enpoint fix
