### ISSUE TITLE
TODO 2

### ISSUE THREAD

**Issue by michelson** [chaskiq/chaskiq#6]
+ [x] pagination on message in chat view
+ [x] reads on old messages not quite there
+ [x] fix uploads on editor
+ [x] remove atlaskit
